stages:
  - notification_start
  - package
  - notification_fail
  - notification_success_pkg
  - extra
  - notification_fail
  - notification_success_extra

before_script:
  - bundle install --binstubs --path ~/gems

Ubuntu 12.04:
  stage: package
  script:
  - ssh -vvT git@dev.gitlab.org
  - make do_release
  tags:
  - ubuntu1204
  except:
  - branches
Ubuntu 14.04:
  stage: package
  script:
  - ssh -vvT git@dev.gitlab.org
  - make do_release
  tags:
  - ubuntu1404
  except:
  - branches
Debian 7:
  stage: package
  script:
  - ssh -vvT git@dev.gitlab.org
  - make do_release
  tags:
  - debian7
  except:
  - branches
Centos 6:
  stage: package
  script:
  - ssh -vvT git@dev.gitlab.org
  - make do_release
  tags:
  - centos6
  except:
  - branches
Centos 7:
  stage: package
  script:
  - ssh -vvT git@dev.gitlab.org
  - make do_release
  tags:
  - centos7
  except:
  - branches
Ubuntu 12.04 master:
  stage: package
  script:
  - ssh -vvT git@dev.gitlab.org
  - make test
  tags:
  - ubuntu1204
  except:
  - tags
Ubuntu 14.04 master:
  stage: package
  script:
  - ssh -vvT git@dev.gitlab.org
  - make test
  tags:
  - ubuntu1404
  except:
  - tags
Debian 7 master:
  stage: package
  script:
  - ssh -vvT git@dev.gitlab.org
  - make test
  tags:
  - debian7
  except:
  - tags
CentOS 6 master:
  stage: package
  script:
  - ssh -vvT git@dev.gitlab.org
  - make test
  tags:
  - centos6
  except:
  - tags
CentOS 7 master:
  stage: package
  script:
  - ssh -vvT git@dev.gitlab.org
  - make test
  tags:
  - centos7
  except:
  - tags
Debian 8:
  stage: package
  script:
  - ssh -vvT git@dev.gitlab.org
  - make do_release
  tags:
  - debian8
  except:
  - branches
Debian 8 master:
  stage: package
  script:
  - ssh -vvT git@dev.gitlab.org
  - make test
  tags:
  - debian8
  except:
  - tags
Raspberry Pi 2 master:
  stage: extra
  script:
  - if ./support/is_gitlab_ee.sh; then exit 0; else make test;fi
  tags:
  - RaspberryPi2-branch
  except:
  - tags
Raspberry Pi 2 wheezy:
  stage: extra
  script:
  - if ./support/is_gitlab_ee.sh; then exit 0; else make do_rpi2_release;fi
  tags:
  - RaspberryPi2-tag
  except:
  - branches
Raspberry Pi 2 jessie:
  stage: extra
  script:
  - if ./support/is_gitlab_ee.sh; then exit 0; else make do_rpi2_release;fi
  tags:
  - RaspberryPi2-jessie-tag
  except:
  - branches
Docker master:
  stage: extra
  script:
  - if ! ./support/is_gitlab_ee.sh; then make do_docker_master; fi
  tags:
  - docker-build
  except:
  - tags
Docker:
  stage: extra
  script:
  - make do_docker_release
  tags:
  - docker-build
  except:
  - branches

notify:slack:
  stage: notification_fail
  script:
    - ./support/notify_slack.sh "#omnibus-builds" "Build on \`$CI_BUILD_REF_NAME\` failed! Commit \`$(git log -1 --oneline)\` See <https://dev.gitlab.org/gitlab/omnibus-gitlab/commit/"$CI_BUILD_REF"/builds>"
  when: on_failure

notify:slack:
  stage: notification_success_pkg
  script:
    - ./support/notify_slack.sh "#omnibus-builds" "Package build on \`$CI_BUILD_REF_NAME\` finished! Commit \`$(git log -1 --oneline)\` See <https://dev.gitlab.org/gitlab/omnibus-gitlab/commit/"$CI_BUILD_REF"/builds>"
  when: on_success

notify:slack:
  stage: notification_success_extra
  script:
    - ./support/notify_slack.sh "#omnibus-builds" "Extra packages (Docker, RPI2) built on \`$CI_BUILD_REF_NAME\`! Commit \`$(git log -1 --oneline)\` See <https://dev.gitlab.org/gitlab/omnibus-gitlab/commit/"$CI_BUILD_REF"/builds>"
  when: on_success

notify:slack:
  stage: notification_start
  script:
    - ./support/notify_slack.sh "#omnibus-builds" "Build on \`$CI_BUILD_REF_NAME\` started! See <https://dev.gitlab.org/gitlab/omnibus-gitlab/commit/"$CI_BUILD_REF"/builds>"
  when: always
  only:
    - tags@gitlab/omnibus-gitlab
