---
# Extended Markdown configuration to enforce no-trailing-spaces rule
# To use this configuration, in doc directory run:
#   markdownlint-cli2-config .markdownlint/.markdownlint.yml '**/*.md'
extends: "../../.markdownlint.yml"
no-trailing-spaces: true
