---
# Extended Markdown configuration to enforce no-trailing-spaces rule
# To use this configuration, in the project directory run:
#   markdownlint-cli2 --config doc/.markdownlint/.markdownlint-cli2.yaml 'doc/**/*.md'
config:
  extends: "../../.markdownlint-cli2.yaml"
  no-trailing-spaces: true
